name: lint

on:
    pull_request:
        branches: [master]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm run lint
